version: "3"

services:
  grafana:
    image: grafana/grafana:6.3.2
    ports:
      - 3000:3000
  prometheus:
    image: prom/prometheus:v2.5.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
